# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChintanGohelAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SSTwitterLogin'
  pod 'SDWebImage', '5.10.0'
  # Pods for ChintanGohelAssignment

  target 'ChintanGohelAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChintanGohelAssignmentUITests' do
    # Pods for testing
  end

end
